### ISSUE TITLE
誤字(自然言語処理の基礎TensorFlow)

### ISSUE THREAD

**Issue by YoshidaTatsuya** [kikagaku/KIKAGAKU_Issues#18]
２ヶ所発見しました！ご確認ください

<誤>
リンクこれまでも重要な部分だけを伝えてくれるサイトやアプリがありましたが、この作業にはたくさんの人手がいりました。
<正>
これまでも重要な部分だけを伝えてくれるサイトやアプリがありましたが、この作業にはたくさんの人手がいりました。

<誤>
単語の係り受けなど、就職関係を決める処理
<正>
単語の係り受けなど、修飾関係を決める処理

**Comment by mourinho384** [comment]
MNISTやCIFAR10などの箇所の初めで、GPUの使用可能かどうか聞かれます。しかし自分は使用可能ではないようですが、そのままCPUで行いました。
問題はないのでしょうか？

# GPU が使用可能であることを確認
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18122461916576308236
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 602115333499001764
physical_device_desc: "device: XLA_CPU device"

**Comment by kikagaku** [comment]
@YoshidaTatsuya 
ご指摘ありがとうございます！
こちら完了修正いたしました。本番環境に反映後 Issue を閉じます。
今後もよろしくお願いいたします。

@mourinho384 
ありがとうございます！
GPU を使用していなくても学習に問題はありませんが、時間がかかってしまいます。GPU の使用をおすすめします！
GPU の環境構築に関しては、**はじめに**の実行環境の章で紹介していますので下のリンク先を参照してください。
・https://www.kikagaku.ai/tutorial/guide_for_beginners/learn/platform_environment#google-colaboratory-%E3%81%AE%E5%9F%BA%E6%9C%AC

今後もよろしくお願いいたします。
