### ISSUE TITLE
数式の確認（ディープラーニングの基礎（TensorFlow））

### ISSUE THREAD

**Issue by at946** [kikagaku/KIKAGAKU_Issues#19]
ニューラルネットワークの数学（逆伝播）・誤差逆伝播法の数式について質問です。
https://www.kikagaku.ai/tutorial/basic_of_deep_learning/learn/tensorflow_neural_network_basic_backward#%E8%AA%A4%E5%B7%AE%E9%80%86%E4%BC%9D%E6%92%AD%E6%B3%95

「パラメータの更新量の算出」において、

<img src="https://latex.codecogs.com/gif.latex?L&space;=&space;(t-y)">
<img src="https://latex.codecogs.com/gif.latex?y&space;=&space;w_{7}&space;z_{11}&space;&plus;&space;w_{8}&space;z_{12}">

に対して

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;L}{\partial&space;y}&space;=&space;2(t&space;-&space;w_{7}z_{11}&space;-&space;w_{8}z_{12})">

と計算されていますが、

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;L}{\partial&space;y}&space;=&space;-2(t&space;-&space;w_{7}z_{11}&space;-&space;w_{8}z_{12})">

ではないでしょうか？

また、

<img src="https://latex.codecogs.com/gif.latex?\begin{eqnarry}&space;\frac{\partial&space;L}{\partial&space;w_{7}}&space;&&space;=&space;&&space;\frac{\partial&space;L}{\partial&space;y}&space;\frac{\partial&space;y}{\partial&space;w_{7}}&space;\\&space;&&space;=&space;&&space;2(t&space;-&space;w_{7}z_{11}&space;-&space;w_{8}z_{12})&space;\times&space;z_{11}&space;\\&space;&&space;=&space;&&space;2&space;\times&space;11&space;(10&space;-&space;3&space;\times&space;0&space;-&space;2&space;\times&space;11)&space;\end{eqnarray}">

と計算されていますが、

<img src="https://latex.codecogs.com/gif.latex?\begin{eqnarry}&space;z_{11}&space;&=&&space;11&space;\\&space;z_{12}&space;&=&&space;0&space;\end{eqnarray}">

の代入が誤っている気がします。

**Comment by kikagaku** [comment]
@at946 様
いつも KIKAGAKU を利用していただき、ありがとうございます。

ご指摘のとおり、参照する数値、微分の計算に誤りがありました。
本番環境でも修正完了しておりますので、ご確認ください。

![ニューラルネットワークの理論（逆伝播）_修正](https://user-images.githubusercontent.com/28823042/81514643-2fbe3600-936b-11ea-977a-13245313049c.png)

今後ともよろしくお願いいたします。
